# Generated by Django 3.1.3 on 2021-02-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='firstTeamScore',
            new_name='first_team_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='secondTeamScore',
            new_name='second_team_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='firstTeam',
            new_name='first_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='roundNumber',
            new_name='round_number',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='secondTeam',
            new_name='second_team',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='numberOfTeams',
            new_name='number_of_teams',
        ),
    ]
