# Generated by Django 3.1.6 on 2021-02-15 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0003_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
