# Generated by Django 3.1.6 on 2021-02-23 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0007_auto_20210217_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 2, 23, 14, 17, 45, 708863)),
        ),
    ]
