# Generated by Django 3.1.6 on 2021-02-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0011_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Bracket',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
    ]
