# Generated by Django 3.1.6 on 2021-02-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0013_auto_20210225_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='match',
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ManyToManyField(to='Tournament.Match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournament.tournament')),
            ],
        ),
    ]
