# Generated by Django 3.1.6 on 2021-02-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0014_auto_20210226_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='match',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='first_team_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tournament.pool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='second_team_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='teams',
            field=models.ManyToManyField(to='Tournament.Team'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
